# Generated by Django 5.1 on 2024-10-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_alter_curso_capacidad'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('Estado', models.CharField(max_length=10)),
                ('Nota', models.FloatField()),
                ('Curso_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.curso')),
                ('Estudiante_id', models.ForeignKey(limit_choices_to={'rol': 'estudiante'}, on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'db_table': 'Estudiante_Curso',
            },
        ),
    ]
